# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/elgood/Code/eclipse/Streaming-c++/SAM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/elgood/Code/eclipse/Streaming-c++/SAM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elgood/Code/eclipse/Streaming-c++/SAM/CMakeFiles /Users/elgood/Code/eclipse/Streaming-c++/SAM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elgood/Code/eclipse/Streaming-c++/SAM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NetflowLib

# Build rule for target.
NetflowLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetflowLib
.PHONY : NetflowLib

# fast build rule for target.
NetflowLib/fast:
	$(MAKE) -f CMakeFiles/NetflowLib.dir/build.make CMakeFiles/NetflowLib.dir/build
.PHONY : NetflowLib/fast

#=============================================================================
# Target rules for targets named PushPull

# Build rule for target.
PushPull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PushPull
.PHONY : PushPull

# fast build rule for target.
PushPull/fast:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/build
.PHONY : PushPull/fast

#=============================================================================
# Target rules for targets named ReadSocketLib

# Build rule for target.
ReadSocketLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReadSocketLib
.PHONY : ReadSocketLib

# fast build rule for target.
ReadSocketLib/fast:
	$(MAKE) -f CMakeFiles/ReadSocketLib.dir/build.make CMakeFiles/ReadSocketLib.dir/build
.PHONY : ReadSocketLib/fast

#=============================================================================
# Target rules for targets named ReadSocket

# Build rule for target.
ReadSocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReadSocket
.PHONY : ReadSocket

# fast build rule for target.
ReadSocket/fast:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/build
.PHONY : ReadSocket/fast

NetflowSrc/Netflow.o: NetflowSrc/Netflow.cpp.o

.PHONY : NetflowSrc/Netflow.o

# target to build an object file
NetflowSrc/Netflow.cpp.o:
	$(MAKE) -f CMakeFiles/NetflowLib.dir/build.make CMakeFiles/NetflowLib.dir/NetflowSrc/Netflow.cpp.o
.PHONY : NetflowSrc/Netflow.cpp.o

NetflowSrc/Netflow.i: NetflowSrc/Netflow.cpp.i

.PHONY : NetflowSrc/Netflow.i

# target to preprocess a source file
NetflowSrc/Netflow.cpp.i:
	$(MAKE) -f CMakeFiles/NetflowLib.dir/build.make CMakeFiles/NetflowLib.dir/NetflowSrc/Netflow.cpp.i
.PHONY : NetflowSrc/Netflow.cpp.i

NetflowSrc/Netflow.s: NetflowSrc/Netflow.cpp.s

.PHONY : NetflowSrc/Netflow.s

# target to generate assembly for a file
NetflowSrc/Netflow.cpp.s:
	$(MAKE) -f CMakeFiles/NetflowLib.dir/build.make CMakeFiles/NetflowLib.dir/NetflowSrc/Netflow.cpp.s
.PHONY : NetflowSrc/Netflow.cpp.s

PushPullSrc/AbstractConsumer.o: PushPullSrc/AbstractConsumer.cpp.o

.PHONY : PushPullSrc/AbstractConsumer.o

# target to build an object file
PushPullSrc/AbstractConsumer.cpp.o:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/AbstractConsumer.cpp.o
.PHONY : PushPullSrc/AbstractConsumer.cpp.o

PushPullSrc/AbstractConsumer.i: PushPullSrc/AbstractConsumer.cpp.i

.PHONY : PushPullSrc/AbstractConsumer.i

# target to preprocess a source file
PushPullSrc/AbstractConsumer.cpp.i:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/AbstractConsumer.cpp.i
.PHONY : PushPullSrc/AbstractConsumer.cpp.i

PushPullSrc/AbstractConsumer.s: PushPullSrc/AbstractConsumer.cpp.s

.PHONY : PushPullSrc/AbstractConsumer.s

# target to generate assembly for a file
PushPullSrc/AbstractConsumer.cpp.s:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/AbstractConsumer.cpp.s
.PHONY : PushPullSrc/AbstractConsumer.cpp.s

PushPullSrc/BaseProducer.o: PushPullSrc/BaseProducer.cpp.o

.PHONY : PushPullSrc/BaseProducer.o

# target to build an object file
PushPullSrc/BaseProducer.cpp.o:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/BaseProducer.cpp.o
.PHONY : PushPullSrc/BaseProducer.cpp.o

PushPullSrc/BaseProducer.i: PushPullSrc/BaseProducer.cpp.i

.PHONY : PushPullSrc/BaseProducer.i

# target to preprocess a source file
PushPullSrc/BaseProducer.cpp.i:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/BaseProducer.cpp.i
.PHONY : PushPullSrc/BaseProducer.cpp.i

PushPullSrc/BaseProducer.s: PushPullSrc/BaseProducer.cpp.s

.PHONY : PushPullSrc/BaseProducer.s

# target to generate assembly for a file
PushPullSrc/BaseProducer.cpp.s:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/BaseProducer.cpp.s
.PHONY : PushPullSrc/BaseProducer.cpp.s

PushPullSrc/TestPushPull.o: PushPullSrc/TestPushPull.cpp.o

.PHONY : PushPullSrc/TestPushPull.o

# target to build an object file
PushPullSrc/TestPushPull.cpp.o:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/TestPushPull.cpp.o
.PHONY : PushPullSrc/TestPushPull.cpp.o

PushPullSrc/TestPushPull.i: PushPullSrc/TestPushPull.cpp.i

.PHONY : PushPullSrc/TestPushPull.i

# target to preprocess a source file
PushPullSrc/TestPushPull.cpp.i:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/TestPushPull.cpp.i
.PHONY : PushPullSrc/TestPushPull.cpp.i

PushPullSrc/TestPushPull.s: PushPullSrc/TestPushPull.cpp.s

.PHONY : PushPullSrc/TestPushPull.s

# target to generate assembly for a file
PushPullSrc/TestPushPull.cpp.s:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/TestPushPull.cpp.s
.PHONY : PushPullSrc/TestPushPull.cpp.s

PushPullSrc/ZeroMQPushPull.o: PushPullSrc/ZeroMQPushPull.cpp.o

.PHONY : PushPullSrc/ZeroMQPushPull.o

# target to build an object file
PushPullSrc/ZeroMQPushPull.cpp.o:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/ZeroMQPushPull.cpp.o
.PHONY : PushPullSrc/ZeroMQPushPull.cpp.o

PushPullSrc/ZeroMQPushPull.i: PushPullSrc/ZeroMQPushPull.cpp.i

.PHONY : PushPullSrc/ZeroMQPushPull.i

# target to preprocess a source file
PushPullSrc/ZeroMQPushPull.cpp.i:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/ZeroMQPushPull.cpp.i
.PHONY : PushPullSrc/ZeroMQPushPull.cpp.i

PushPullSrc/ZeroMQPushPull.s: PushPullSrc/ZeroMQPushPull.cpp.s

.PHONY : PushPullSrc/ZeroMQPushPull.s

# target to generate assembly for a file
PushPullSrc/ZeroMQPushPull.cpp.s:
	$(MAKE) -f CMakeFiles/PushPull.dir/build.make CMakeFiles/PushPull.dir/PushPullSrc/ZeroMQPushPull.cpp.s
.PHONY : PushPullSrc/ZeroMQPushPull.cpp.s

ReadSocketSrc/ReadSocket.o: ReadSocketSrc/ReadSocket.cpp.o

.PHONY : ReadSocketSrc/ReadSocket.o

# target to build an object file
ReadSocketSrc/ReadSocket.cpp.o:
	$(MAKE) -f CMakeFiles/ReadSocketLib.dir/build.make CMakeFiles/ReadSocketLib.dir/ReadSocketSrc/ReadSocket.cpp.o
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/ReadSocket.cpp.o
.PHONY : ReadSocketSrc/ReadSocket.cpp.o

ReadSocketSrc/ReadSocket.i: ReadSocketSrc/ReadSocket.cpp.i

.PHONY : ReadSocketSrc/ReadSocket.i

# target to preprocess a source file
ReadSocketSrc/ReadSocket.cpp.i:
	$(MAKE) -f CMakeFiles/ReadSocketLib.dir/build.make CMakeFiles/ReadSocketLib.dir/ReadSocketSrc/ReadSocket.cpp.i
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/ReadSocket.cpp.i
.PHONY : ReadSocketSrc/ReadSocket.cpp.i

ReadSocketSrc/ReadSocket.s: ReadSocketSrc/ReadSocket.cpp.s

.PHONY : ReadSocketSrc/ReadSocket.s

# target to generate assembly for a file
ReadSocketSrc/ReadSocket.cpp.s:
	$(MAKE) -f CMakeFiles/ReadSocketLib.dir/build.make CMakeFiles/ReadSocketLib.dir/ReadSocketSrc/ReadSocket.cpp.s
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/ReadSocket.cpp.s
.PHONY : ReadSocketSrc/ReadSocket.cpp.s

ReadSocketSrc/TestNCSpeed.o: ReadSocketSrc/TestNCSpeed.cpp.o

.PHONY : ReadSocketSrc/TestNCSpeed.o

# target to build an object file
ReadSocketSrc/TestNCSpeed.cpp.o:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/TestNCSpeed.cpp.o
.PHONY : ReadSocketSrc/TestNCSpeed.cpp.o

ReadSocketSrc/TestNCSpeed.i: ReadSocketSrc/TestNCSpeed.cpp.i

.PHONY : ReadSocketSrc/TestNCSpeed.i

# target to preprocess a source file
ReadSocketSrc/TestNCSpeed.cpp.i:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/TestNCSpeed.cpp.i
.PHONY : ReadSocketSrc/TestNCSpeed.cpp.i

ReadSocketSrc/TestNCSpeed.s: ReadSocketSrc/TestNCSpeed.cpp.s

.PHONY : ReadSocketSrc/TestNCSpeed.s

# target to generate assembly for a file
ReadSocketSrc/TestNCSpeed.cpp.s:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/TestNCSpeed.cpp.s
.PHONY : ReadSocketSrc/TestNCSpeed.cpp.s

ReadSocketSrc/ZeroMqPushPull.o: ReadSocketSrc/ZeroMqPushPull.cpp.o

.PHONY : ReadSocketSrc/ZeroMqPushPull.o

# target to build an object file
ReadSocketSrc/ZeroMqPushPull.cpp.o:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/ZeroMqPushPull.cpp.o
.PHONY : ReadSocketSrc/ZeroMqPushPull.cpp.o

ReadSocketSrc/ZeroMqPushPull.i: ReadSocketSrc/ZeroMqPushPull.cpp.i

.PHONY : ReadSocketSrc/ZeroMqPushPull.i

# target to preprocess a source file
ReadSocketSrc/ZeroMqPushPull.cpp.i:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/ZeroMqPushPull.cpp.i
.PHONY : ReadSocketSrc/ZeroMqPushPull.cpp.i

ReadSocketSrc/ZeroMqPushPull.s: ReadSocketSrc/ZeroMqPushPull.cpp.s

.PHONY : ReadSocketSrc/ZeroMqPushPull.s

# target to generate assembly for a file
ReadSocketSrc/ZeroMqPushPull.cpp.s:
	$(MAKE) -f CMakeFiles/ReadSocket.dir/build.make CMakeFiles/ReadSocket.dir/ReadSocketSrc/ZeroMqPushPull.cpp.s
.PHONY : ReadSocketSrc/ZeroMqPushPull.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... NetflowLib"
	@echo "... edit_cache"
	@echo "... PushPull"
	@echo "... ReadSocketLib"
	@echo "... ReadSocket"
	@echo "... NetflowSrc/Netflow.o"
	@echo "... NetflowSrc/Netflow.i"
	@echo "... NetflowSrc/Netflow.s"
	@echo "... PushPullSrc/AbstractConsumer.o"
	@echo "... PushPullSrc/AbstractConsumer.i"
	@echo "... PushPullSrc/AbstractConsumer.s"
	@echo "... PushPullSrc/BaseProducer.o"
	@echo "... PushPullSrc/BaseProducer.i"
	@echo "... PushPullSrc/BaseProducer.s"
	@echo "... PushPullSrc/TestPushPull.o"
	@echo "... PushPullSrc/TestPushPull.i"
	@echo "... PushPullSrc/TestPushPull.s"
	@echo "... PushPullSrc/ZeroMQPushPull.o"
	@echo "... PushPullSrc/ZeroMQPushPull.i"
	@echo "... PushPullSrc/ZeroMQPushPull.s"
	@echo "... ReadSocketSrc/ReadSocket.o"
	@echo "... ReadSocketSrc/ReadSocket.i"
	@echo "... ReadSocketSrc/ReadSocket.s"
	@echo "... ReadSocketSrc/TestNCSpeed.o"
	@echo "... ReadSocketSrc/TestNCSpeed.i"
	@echo "... ReadSocketSrc/TestNCSpeed.s"
	@echo "... ReadSocketSrc/ZeroMqPushPull.o"
	@echo "... ReadSocketSrc/ZeroMqPushPull.i"
	@echo "... ReadSocketSrc/ZeroMqPushPull.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

