// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetflowEdgeRequest.proto

#include "NetflowEdgeRequest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace sam {
class NetflowEdgeRequest_SimpleEdgeConditionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NetflowEdgeRequest_SimpleEdgeCondition>
      _instance;
} _NetflowEdgeRequest_SimpleEdgeCondition_default_instance_;
class NetflowEdgeRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NetflowEdgeRequest>
      _instance;
} _NetflowEdgeRequest_default_instance_;
}  // namespace sam
namespace protobuf_NetflowEdgeRequest_2eproto {
void InitDefaultsNetflowEdgeRequest_SimpleEdgeConditionImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::sam::_NetflowEdgeRequest_SimpleEdgeCondition_default_instance_;
    new (ptr) ::sam::NetflowEdgeRequest_SimpleEdgeCondition();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sam::NetflowEdgeRequest_SimpleEdgeCondition::InitAsDefaultInstance();
}

void InitDefaultsNetflowEdgeRequest_SimpleEdgeCondition() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNetflowEdgeRequest_SimpleEdgeConditionImpl);
}

void InitDefaultsNetflowEdgeRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest_SimpleEdgeCondition();
  {
    void* ptr = &::sam::_NetflowEdgeRequest_default_instance_;
    new (ptr) ::sam::NetflowEdgeRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sam::NetflowEdgeRequest::InitAsDefaultInstance();
}

void InitDefaultsNetflowEdgeRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNetflowEdgeRequestImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest_SimpleEdgeCondition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest_SimpleEdgeCondition, field_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest_SimpleEdgeCondition, operator__),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest_SimpleEdgeCondition, rside_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, sourceip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, destip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, terminate_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, conditions_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sam::NetflowEdgeRequest_SimpleEdgeCondition)},
  { 8, -1, sizeof(::sam::NetflowEdgeRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::sam::_NetflowEdgeRequest_SimpleEdgeCondition_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::sam::_NetflowEdgeRequest_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "NetflowEdgeRequest.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030NetflowEdgeRequest.proto\022\003sam\"\321\001\n\022Netf"
      "lowEdgeRequest\022\020\n\010sourceIP\030\001 \001(\t\022\016\n\006dest"
      "IP\030\002 \001(\t\022\021\n\tterminate\030\003 \001(\010\022\?\n\ncondition"
      "s\030\004 \003(\0132+.sam.NetflowEdgeRequest.SimpleE"
      "dgeCondition\032E\n\023SimpleEdgeCondition\022\r\n\005f"
      "ield\030\001 \001(\t\022\020\n\010operator\030\002 \001(\t\022\r\n\005rside\030\003 "
      "\001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 251);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NetflowEdgeRequest.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_NetflowEdgeRequest_2eproto
namespace sam {

// ===================================================================

void NetflowEdgeRequest_SimpleEdgeCondition::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NetflowEdgeRequest_SimpleEdgeCondition::kFieldFieldNumber;
const int NetflowEdgeRequest_SimpleEdgeCondition::kOperatorFieldNumber;
const int NetflowEdgeRequest_SimpleEdgeCondition::kRsideFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NetflowEdgeRequest_SimpleEdgeCondition::NetflowEdgeRequest_SimpleEdgeCondition()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest_SimpleEdgeCondition();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sam.NetflowEdgeRequest.SimpleEdgeCondition)
}
NetflowEdgeRequest_SimpleEdgeCondition::NetflowEdgeRequest_SimpleEdgeCondition(const NetflowEdgeRequest_SimpleEdgeCondition& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  field_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.field().size() > 0) {
    field_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field_);
  }
  operator__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operator_().size() > 0) {
    operator__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operator__);
  }
  rside_ = from.rside_;
  // @@protoc_insertion_point(copy_constructor:sam.NetflowEdgeRequest.SimpleEdgeCondition)
}

void NetflowEdgeRequest_SimpleEdgeCondition::SharedCtor() {
  field_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operator__.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rside_ = 0;
  _cached_size_ = 0;
}

NetflowEdgeRequest_SimpleEdgeCondition::~NetflowEdgeRequest_SimpleEdgeCondition() {
  // @@protoc_insertion_point(destructor:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  SharedDtor();
}

void NetflowEdgeRequest_SimpleEdgeCondition::SharedDtor() {
  field_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operator__.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NetflowEdgeRequest_SimpleEdgeCondition::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NetflowEdgeRequest_SimpleEdgeCondition::descriptor() {
  ::protobuf_NetflowEdgeRequest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NetflowEdgeRequest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NetflowEdgeRequest_SimpleEdgeCondition& NetflowEdgeRequest_SimpleEdgeCondition::default_instance() {
  ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest_SimpleEdgeCondition();
  return *internal_default_instance();
}

NetflowEdgeRequest_SimpleEdgeCondition* NetflowEdgeRequest_SimpleEdgeCondition::New(::google::protobuf::Arena* arena) const {
  NetflowEdgeRequest_SimpleEdgeCondition* n = new NetflowEdgeRequest_SimpleEdgeCondition;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NetflowEdgeRequest_SimpleEdgeCondition::Clear() {
// @@protoc_insertion_point(message_clear_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  field_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operator__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rside_ = 0;
  _internal_metadata_.Clear();
}

bool NetflowEdgeRequest_SimpleEdgeCondition::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string field = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->field().data(), static_cast<int>(this->field().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sam.NetflowEdgeRequest.SimpleEdgeCondition.field"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operator = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operator_()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operator_().data(), static_cast<int>(this->operator_().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sam.NetflowEdgeRequest.SimpleEdgeCondition.operator"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 rside = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rside_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  return false;
#undef DO_
}

void NetflowEdgeRequest_SimpleEdgeCondition::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string field = 1;
  if (this->field().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field().data(), static_cast<int>(this->field().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.SimpleEdgeCondition.field");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field(), output);
  }

  // string operator = 2;
  if (this->operator_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operator_().data(), static_cast<int>(this->operator_().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.SimpleEdgeCondition.operator");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->operator_(), output);
  }

  // int32 rside = 3;
  if (this->rside() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rside(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sam.NetflowEdgeRequest.SimpleEdgeCondition)
}

::google::protobuf::uint8* NetflowEdgeRequest_SimpleEdgeCondition::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string field = 1;
  if (this->field().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->field().data(), static_cast<int>(this->field().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.SimpleEdgeCondition.field");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field(), target);
  }

  // string operator = 2;
  if (this->operator_().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operator_().data(), static_cast<int>(this->operator_().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.SimpleEdgeCondition.operator");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->operator_(), target);
  }

  // int32 rside = 3;
  if (this->rside() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rside(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  return target;
}

size_t NetflowEdgeRequest_SimpleEdgeCondition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string field = 1;
  if (this->field().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->field());
  }

  // string operator = 2;
  if (this->operator_().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operator_());
  }

  // int32 rside = 3;
  if (this->rside() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rside());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NetflowEdgeRequest_SimpleEdgeCondition::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  GOOGLE_DCHECK_NE(&from, this);
  const NetflowEdgeRequest_SimpleEdgeCondition* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NetflowEdgeRequest_SimpleEdgeCondition>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sam.NetflowEdgeRequest.SimpleEdgeCondition)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sam.NetflowEdgeRequest.SimpleEdgeCondition)
    MergeFrom(*source);
  }
}

void NetflowEdgeRequest_SimpleEdgeCondition::MergeFrom(const NetflowEdgeRequest_SimpleEdgeCondition& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.field().size() > 0) {

    field_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field_);
  }
  if (from.operator_().size() > 0) {

    operator__.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operator__);
  }
  if (from.rside() != 0) {
    set_rside(from.rside());
  }
}

void NetflowEdgeRequest_SimpleEdgeCondition::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetflowEdgeRequest_SimpleEdgeCondition::CopyFrom(const NetflowEdgeRequest_SimpleEdgeCondition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sam.NetflowEdgeRequest.SimpleEdgeCondition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetflowEdgeRequest_SimpleEdgeCondition::IsInitialized() const {
  return true;
}

void NetflowEdgeRequest_SimpleEdgeCondition::Swap(NetflowEdgeRequest_SimpleEdgeCondition* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NetflowEdgeRequest_SimpleEdgeCondition::InternalSwap(NetflowEdgeRequest_SimpleEdgeCondition* other) {
  using std::swap;
  field_.Swap(&other->field_);
  operator__.Swap(&other->operator__);
  swap(rside_, other->rside_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NetflowEdgeRequest_SimpleEdgeCondition::GetMetadata() const {
  protobuf_NetflowEdgeRequest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NetflowEdgeRequest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NetflowEdgeRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NetflowEdgeRequest::kSourceIPFieldNumber;
const int NetflowEdgeRequest::kDestIPFieldNumber;
const int NetflowEdgeRequest::kTerminateFieldNumber;
const int NetflowEdgeRequest::kConditionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NetflowEdgeRequest::NetflowEdgeRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sam.NetflowEdgeRequest)
}
NetflowEdgeRequest::NetflowEdgeRequest(const NetflowEdgeRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      conditions_(from.conditions_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sourceip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sourceip().size() > 0) {
    sourceip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sourceip_);
  }
  destip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.destip().size() > 0) {
    destip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destip_);
  }
  terminate_ = from.terminate_;
  // @@protoc_insertion_point(copy_constructor:sam.NetflowEdgeRequest)
}

void NetflowEdgeRequest::SharedCtor() {
  sourceip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  terminate_ = false;
  _cached_size_ = 0;
}

NetflowEdgeRequest::~NetflowEdgeRequest() {
  // @@protoc_insertion_point(destructor:sam.NetflowEdgeRequest)
  SharedDtor();
}

void NetflowEdgeRequest::SharedDtor() {
  sourceip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NetflowEdgeRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NetflowEdgeRequest::descriptor() {
  ::protobuf_NetflowEdgeRequest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NetflowEdgeRequest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NetflowEdgeRequest& NetflowEdgeRequest::default_instance() {
  ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest();
  return *internal_default_instance();
}

NetflowEdgeRequest* NetflowEdgeRequest::New(::google::protobuf::Arena* arena) const {
  NetflowEdgeRequest* n = new NetflowEdgeRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NetflowEdgeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sam.NetflowEdgeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  conditions_.Clear();
  sourceip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  terminate_ = false;
  _internal_metadata_.Clear();
}

bool NetflowEdgeRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sam.NetflowEdgeRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string sourceIP = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sourceip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sourceip().data(), static_cast<int>(this->sourceip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sam.NetflowEdgeRequest.sourceIP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string destIP = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_destip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->destip().data(), static_cast<int>(this->destip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sam.NetflowEdgeRequest.destIP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool terminate = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &terminate_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .sam.NetflowEdgeRequest.SimpleEdgeCondition conditions = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_conditions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sam.NetflowEdgeRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sam.NetflowEdgeRequest)
  return false;
#undef DO_
}

void NetflowEdgeRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sam.NetflowEdgeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sourceIP = 1;
  if (this->sourceip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sourceip().data(), static_cast<int>(this->sourceip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.sourceIP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->sourceip(), output);
  }

  // string destIP = 2;
  if (this->destip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->destip().data(), static_cast<int>(this->destip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.destIP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->destip(), output);
  }

  // bool terminate = 3;
  if (this->terminate() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->terminate(), output);
  }

  // repeated .sam.NetflowEdgeRequest.SimpleEdgeCondition conditions = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->conditions_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->conditions(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sam.NetflowEdgeRequest)
}

::google::protobuf::uint8* NetflowEdgeRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sam.NetflowEdgeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sourceIP = 1;
  if (this->sourceip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sourceip().data(), static_cast<int>(this->sourceip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.sourceIP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->sourceip(), target);
  }

  // string destIP = 2;
  if (this->destip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->destip().data(), static_cast<int>(this->destip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.destIP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->destip(), target);
  }

  // bool terminate = 3;
  if (this->terminate() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->terminate(), target);
  }

  // repeated .sam.NetflowEdgeRequest.SimpleEdgeCondition conditions = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->conditions_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->conditions(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sam.NetflowEdgeRequest)
  return target;
}

size_t NetflowEdgeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sam.NetflowEdgeRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .sam.NetflowEdgeRequest.SimpleEdgeCondition conditions = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->conditions_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->conditions(static_cast<int>(i)));
    }
  }

  // string sourceIP = 1;
  if (this->sourceip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sourceip());
  }

  // string destIP = 2;
  if (this->destip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destip());
  }

  // bool terminate = 3;
  if (this->terminate() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NetflowEdgeRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sam.NetflowEdgeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NetflowEdgeRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NetflowEdgeRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sam.NetflowEdgeRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sam.NetflowEdgeRequest)
    MergeFrom(*source);
  }
}

void NetflowEdgeRequest::MergeFrom(const NetflowEdgeRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sam.NetflowEdgeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  conditions_.MergeFrom(from.conditions_);
  if (from.sourceip().size() > 0) {

    sourceip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sourceip_);
  }
  if (from.destip().size() > 0) {

    destip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destip_);
  }
  if (from.terminate() != 0) {
    set_terminate(from.terminate());
  }
}

void NetflowEdgeRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sam.NetflowEdgeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetflowEdgeRequest::CopyFrom(const NetflowEdgeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sam.NetflowEdgeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetflowEdgeRequest::IsInitialized() const {
  return true;
}

void NetflowEdgeRequest::Swap(NetflowEdgeRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NetflowEdgeRequest::InternalSwap(NetflowEdgeRequest* other) {
  using std::swap;
  conditions_.InternalSwap(&other->conditions_);
  sourceip_.Swap(&other->sourceip_);
  destip_.Swap(&other->destip_);
  swap(terminate_, other->terminate_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NetflowEdgeRequest::GetMetadata() const {
  protobuf_NetflowEdgeRequest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NetflowEdgeRequest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sam

// @@protoc_insertion_point(global_scope)
