// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetflowEdgeRequest.proto

#ifndef PROTOBUF_NetflowEdgeRequest_2eproto__INCLUDED
#define PROTOBUF_NetflowEdgeRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_NetflowEdgeRequest_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsNetflowEdgeRequestImpl();
void InitDefaultsNetflowEdgeRequest();
inline void InitDefaults() {
  InitDefaultsNetflowEdgeRequest();
}
}  // namespace protobuf_NetflowEdgeRequest_2eproto
namespace sam {
class NetflowEdgeRequest;
class NetflowEdgeRequestDefaultTypeInternal;
extern NetflowEdgeRequestDefaultTypeInternal _NetflowEdgeRequest_default_instance_;
}  // namespace sam
namespace sam {

// ===================================================================

class NetflowEdgeRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sam.NetflowEdgeRequest) */ {
 public:
  NetflowEdgeRequest();
  virtual ~NetflowEdgeRequest();

  NetflowEdgeRequest(const NetflowEdgeRequest& from);

  inline NetflowEdgeRequest& operator=(const NetflowEdgeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NetflowEdgeRequest(NetflowEdgeRequest&& from) noexcept
    : NetflowEdgeRequest() {
    *this = ::std::move(from);
  }

  inline NetflowEdgeRequest& operator=(NetflowEdgeRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NetflowEdgeRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NetflowEdgeRequest* internal_default_instance() {
    return reinterpret_cast<const NetflowEdgeRequest*>(
               &_NetflowEdgeRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NetflowEdgeRequest* other);
  friend void swap(NetflowEdgeRequest& a, NetflowEdgeRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NetflowEdgeRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  NetflowEdgeRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NetflowEdgeRequest& from);
  void MergeFrom(const NetflowEdgeRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NetflowEdgeRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sourceIP = 6;
  void clear_sourceip();
  static const int kSourceIPFieldNumber = 6;
  const ::std::string& sourceip() const;
  void set_sourceip(const ::std::string& value);
  #if LANG_CXX11
  void set_sourceip(::std::string&& value);
  #endif
  void set_sourceip(const char* value);
  void set_sourceip(const char* value, size_t size);
  ::std::string* mutable_sourceip();
  ::std::string* release_sourceip();
  void set_allocated_sourceip(::std::string* sourceip);

  // string destIP = 7;
  void clear_destip();
  static const int kDestIPFieldNumber = 7;
  const ::std::string& destip() const;
  void set_destip(const ::std::string& value);
  #if LANG_CXX11
  void set_destip(::std::string&& value);
  #endif
  void set_destip(const char* value);
  void set_destip(const char* value, size_t size);
  ::std::string* mutable_destip();
  ::std::string* release_destip();
  void set_allocated_destip(::std::string* destip);

  // double startTimeFirst = 1;
  void clear_starttimefirst();
  static const int kStartTimeFirstFieldNumber = 1;
  double starttimefirst() const;
  void set_starttimefirst(double value);

  // double startTimeSecond = 2;
  void clear_starttimesecond();
  static const int kStartTimeSecondFieldNumber = 2;
  double starttimesecond() const;
  void set_starttimesecond(double value);

  // double endTimeFirst = 3;
  void clear_endtimefirst();
  static const int kEndTimeFirstFieldNumber = 3;
  double endtimefirst() const;
  void set_endtimefirst(double value);

  // double endTimeSecond = 4;
  void clear_endtimesecond();
  static const int kEndTimeSecondFieldNumber = 4;
  double endtimesecond() const;
  void set_endtimesecond(double value);

  // uint32 returnNode = 5;
  void clear_returnnode();
  static const int kReturnNodeFieldNumber = 5;
  ::google::protobuf::uint32 returnnode() const;
  void set_returnnode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:sam.NetflowEdgeRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sourceip_;
  ::google::protobuf::internal::ArenaStringPtr destip_;
  double starttimefirst_;
  double starttimesecond_;
  double endtimefirst_;
  double endtimesecond_;
  ::google::protobuf::uint32 returnnode_;
  mutable int _cached_size_;
  friend struct ::protobuf_NetflowEdgeRequest_2eproto::TableStruct;
  friend void ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequestImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NetflowEdgeRequest

// double startTimeFirst = 1;
inline void NetflowEdgeRequest::clear_starttimefirst() {
  starttimefirst_ = 0;
}
inline double NetflowEdgeRequest::starttimefirst() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.startTimeFirst)
  return starttimefirst_;
}
inline void NetflowEdgeRequest::set_starttimefirst(double value) {
  
  starttimefirst_ = value;
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.startTimeFirst)
}

// double startTimeSecond = 2;
inline void NetflowEdgeRequest::clear_starttimesecond() {
  starttimesecond_ = 0;
}
inline double NetflowEdgeRequest::starttimesecond() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.startTimeSecond)
  return starttimesecond_;
}
inline void NetflowEdgeRequest::set_starttimesecond(double value) {
  
  starttimesecond_ = value;
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.startTimeSecond)
}

// double endTimeFirst = 3;
inline void NetflowEdgeRequest::clear_endtimefirst() {
  endtimefirst_ = 0;
}
inline double NetflowEdgeRequest::endtimefirst() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.endTimeFirst)
  return endtimefirst_;
}
inline void NetflowEdgeRequest::set_endtimefirst(double value) {
  
  endtimefirst_ = value;
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.endTimeFirst)
}

// double endTimeSecond = 4;
inline void NetflowEdgeRequest::clear_endtimesecond() {
  endtimesecond_ = 0;
}
inline double NetflowEdgeRequest::endtimesecond() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.endTimeSecond)
  return endtimesecond_;
}
inline void NetflowEdgeRequest::set_endtimesecond(double value) {
  
  endtimesecond_ = value;
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.endTimeSecond)
}

// uint32 returnNode = 5;
inline void NetflowEdgeRequest::clear_returnnode() {
  returnnode_ = 0u;
}
inline ::google::protobuf::uint32 NetflowEdgeRequest::returnnode() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.returnNode)
  return returnnode_;
}
inline void NetflowEdgeRequest::set_returnnode(::google::protobuf::uint32 value) {
  
  returnnode_ = value;
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.returnNode)
}

// string sourceIP = 6;
inline void NetflowEdgeRequest::clear_sourceip() {
  sourceip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NetflowEdgeRequest::sourceip() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.sourceIP)
  return sourceip_.GetNoArena();
}
inline void NetflowEdgeRequest::set_sourceip(const ::std::string& value) {
  
  sourceip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.sourceIP)
}
#if LANG_CXX11
inline void NetflowEdgeRequest::set_sourceip(::std::string&& value) {
  
  sourceip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sam.NetflowEdgeRequest.sourceIP)
}
#endif
inline void NetflowEdgeRequest::set_sourceip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sourceip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sam.NetflowEdgeRequest.sourceIP)
}
inline void NetflowEdgeRequest::set_sourceip(const char* value, size_t size) {
  
  sourceip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sam.NetflowEdgeRequest.sourceIP)
}
inline ::std::string* NetflowEdgeRequest::mutable_sourceip() {
  
  // @@protoc_insertion_point(field_mutable:sam.NetflowEdgeRequest.sourceIP)
  return sourceip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NetflowEdgeRequest::release_sourceip() {
  // @@protoc_insertion_point(field_release:sam.NetflowEdgeRequest.sourceIP)
  
  return sourceip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NetflowEdgeRequest::set_allocated_sourceip(::std::string* sourceip) {
  if (sourceip != NULL) {
    
  } else {
    
  }
  sourceip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sourceip);
  // @@protoc_insertion_point(field_set_allocated:sam.NetflowEdgeRequest.sourceIP)
}

// string destIP = 7;
inline void NetflowEdgeRequest::clear_destip() {
  destip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NetflowEdgeRequest::destip() const {
  // @@protoc_insertion_point(field_get:sam.NetflowEdgeRequest.destIP)
  return destip_.GetNoArena();
}
inline void NetflowEdgeRequest::set_destip(const ::std::string& value) {
  
  destip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sam.NetflowEdgeRequest.destIP)
}
#if LANG_CXX11
inline void NetflowEdgeRequest::set_destip(::std::string&& value) {
  
  destip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sam.NetflowEdgeRequest.destIP)
}
#endif
inline void NetflowEdgeRequest::set_destip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  destip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sam.NetflowEdgeRequest.destIP)
}
inline void NetflowEdgeRequest::set_destip(const char* value, size_t size) {
  
  destip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sam.NetflowEdgeRequest.destIP)
}
inline ::std::string* NetflowEdgeRequest::mutable_destip() {
  
  // @@protoc_insertion_point(field_mutable:sam.NetflowEdgeRequest.destIP)
  return destip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NetflowEdgeRequest::release_destip() {
  // @@protoc_insertion_point(field_release:sam.NetflowEdgeRequest.destIP)
  
  return destip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NetflowEdgeRequest::set_allocated_destip(::std::string* destip) {
  if (destip != NULL) {
    
  } else {
    
  }
  destip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destip);
  // @@protoc_insertion_point(field_set_allocated:sam.NetflowEdgeRequest.destIP)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sam

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NetflowEdgeRequest_2eproto__INCLUDED
