// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetflowEdgeRequest.proto

#include "NetflowEdgeRequest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace sam {
class NetflowEdgeRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NetflowEdgeRequest>
      _instance;
} _NetflowEdgeRequest_default_instance_;
}  // namespace sam
namespace protobuf_NetflowEdgeRequest_2eproto {
void InitDefaultsNetflowEdgeRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::sam::_NetflowEdgeRequest_default_instance_;
    new (ptr) ::sam::NetflowEdgeRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sam::NetflowEdgeRequest::InitAsDefaultInstance();
}

void InitDefaultsNetflowEdgeRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNetflowEdgeRequestImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, starttimefirst_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, starttimesecond_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, endtimefirst_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, endtimesecond_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, returnnode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, sourceip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sam::NetflowEdgeRequest, destip_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sam::NetflowEdgeRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::sam::_NetflowEdgeRequest_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "NetflowEdgeRequest.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030NetflowEdgeRequest.proto\022\003sam\"\250\001\n\022Netf"
      "lowEdgeRequest\022\026\n\016startTimeFirst\030\001 \001(\001\022\027"
      "\n\017startTimeSecond\030\002 \001(\001\022\024\n\014endTimeFirst\030"
      "\003 \001(\001\022\025\n\rendTimeSecond\030\004 \001(\001\022\022\n\nreturnNo"
      "de\030\005 \001(\r\022\020\n\010sourceIP\030\006 \001(\t\022\016\n\006destIP\030\007 \001"
      "(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 210);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "NetflowEdgeRequest.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_NetflowEdgeRequest_2eproto
namespace sam {

// ===================================================================

void NetflowEdgeRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NetflowEdgeRequest::kStartTimeFirstFieldNumber;
const int NetflowEdgeRequest::kStartTimeSecondFieldNumber;
const int NetflowEdgeRequest::kEndTimeFirstFieldNumber;
const int NetflowEdgeRequest::kEndTimeSecondFieldNumber;
const int NetflowEdgeRequest::kReturnNodeFieldNumber;
const int NetflowEdgeRequest::kSourceIPFieldNumber;
const int NetflowEdgeRequest::kDestIPFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NetflowEdgeRequest::NetflowEdgeRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sam.NetflowEdgeRequest)
}
NetflowEdgeRequest::NetflowEdgeRequest(const NetflowEdgeRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sourceip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sourceip().size() > 0) {
    sourceip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sourceip_);
  }
  destip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.destip().size() > 0) {
    destip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destip_);
  }
  ::memcpy(&starttimefirst_, &from.starttimefirst_,
    static_cast<size_t>(reinterpret_cast<char*>(&returnnode_) -
    reinterpret_cast<char*>(&starttimefirst_)) + sizeof(returnnode_));
  // @@protoc_insertion_point(copy_constructor:sam.NetflowEdgeRequest)
}

void NetflowEdgeRequest::SharedCtor() {
  sourceip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&starttimefirst_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&returnnode_) -
      reinterpret_cast<char*>(&starttimefirst_)) + sizeof(returnnode_));
  _cached_size_ = 0;
}

NetflowEdgeRequest::~NetflowEdgeRequest() {
  // @@protoc_insertion_point(destructor:sam.NetflowEdgeRequest)
  SharedDtor();
}

void NetflowEdgeRequest::SharedDtor() {
  sourceip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NetflowEdgeRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NetflowEdgeRequest::descriptor() {
  ::protobuf_NetflowEdgeRequest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NetflowEdgeRequest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NetflowEdgeRequest& NetflowEdgeRequest::default_instance() {
  ::protobuf_NetflowEdgeRequest_2eproto::InitDefaultsNetflowEdgeRequest();
  return *internal_default_instance();
}

NetflowEdgeRequest* NetflowEdgeRequest::New(::google::protobuf::Arena* arena) const {
  NetflowEdgeRequest* n = new NetflowEdgeRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NetflowEdgeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sam.NetflowEdgeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sourceip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&starttimefirst_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&returnnode_) -
      reinterpret_cast<char*>(&starttimefirst_)) + sizeof(returnnode_));
  _internal_metadata_.Clear();
}

bool NetflowEdgeRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sam.NetflowEdgeRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double startTimeFirst = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &starttimefirst_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double startTimeSecond = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &starttimesecond_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double endTimeFirst = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &endtimefirst_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double endTimeSecond = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &endtimesecond_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 returnNode = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &returnnode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sourceIP = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sourceip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sourceip().data(), static_cast<int>(this->sourceip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sam.NetflowEdgeRequest.sourceIP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string destIP = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_destip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->destip().data(), static_cast<int>(this->destip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sam.NetflowEdgeRequest.destIP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sam.NetflowEdgeRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sam.NetflowEdgeRequest)
  return false;
#undef DO_
}

void NetflowEdgeRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sam.NetflowEdgeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double startTimeFirst = 1;
  if (this->starttimefirst() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->starttimefirst(), output);
  }

  // double startTimeSecond = 2;
  if (this->starttimesecond() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->starttimesecond(), output);
  }

  // double endTimeFirst = 3;
  if (this->endtimefirst() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->endtimefirst(), output);
  }

  // double endTimeSecond = 4;
  if (this->endtimesecond() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->endtimesecond(), output);
  }

  // uint32 returnNode = 5;
  if (this->returnnode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->returnnode(), output);
  }

  // string sourceIP = 6;
  if (this->sourceip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sourceip().data(), static_cast<int>(this->sourceip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.sourceIP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->sourceip(), output);
  }

  // string destIP = 7;
  if (this->destip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->destip().data(), static_cast<int>(this->destip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.destIP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->destip(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sam.NetflowEdgeRequest)
}

::google::protobuf::uint8* NetflowEdgeRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sam.NetflowEdgeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double startTimeFirst = 1;
  if (this->starttimefirst() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->starttimefirst(), target);
  }

  // double startTimeSecond = 2;
  if (this->starttimesecond() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->starttimesecond(), target);
  }

  // double endTimeFirst = 3;
  if (this->endtimefirst() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->endtimefirst(), target);
  }

  // double endTimeSecond = 4;
  if (this->endtimesecond() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->endtimesecond(), target);
  }

  // uint32 returnNode = 5;
  if (this->returnnode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->returnnode(), target);
  }

  // string sourceIP = 6;
  if (this->sourceip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sourceip().data(), static_cast<int>(this->sourceip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.sourceIP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->sourceip(), target);
  }

  // string destIP = 7;
  if (this->destip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->destip().data(), static_cast<int>(this->destip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sam.NetflowEdgeRequest.destIP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->destip(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sam.NetflowEdgeRequest)
  return target;
}

size_t NetflowEdgeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sam.NetflowEdgeRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string sourceIP = 6;
  if (this->sourceip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sourceip());
  }

  // string destIP = 7;
  if (this->destip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destip());
  }

  // double startTimeFirst = 1;
  if (this->starttimefirst() != 0) {
    total_size += 1 + 8;
  }

  // double startTimeSecond = 2;
  if (this->starttimesecond() != 0) {
    total_size += 1 + 8;
  }

  // double endTimeFirst = 3;
  if (this->endtimefirst() != 0) {
    total_size += 1 + 8;
  }

  // double endTimeSecond = 4;
  if (this->endtimesecond() != 0) {
    total_size += 1 + 8;
  }

  // uint32 returnNode = 5;
  if (this->returnnode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->returnnode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NetflowEdgeRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sam.NetflowEdgeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NetflowEdgeRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NetflowEdgeRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sam.NetflowEdgeRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sam.NetflowEdgeRequest)
    MergeFrom(*source);
  }
}

void NetflowEdgeRequest::MergeFrom(const NetflowEdgeRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sam.NetflowEdgeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sourceip().size() > 0) {

    sourceip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sourceip_);
  }
  if (from.destip().size() > 0) {

    destip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destip_);
  }
  if (from.starttimefirst() != 0) {
    set_starttimefirst(from.starttimefirst());
  }
  if (from.starttimesecond() != 0) {
    set_starttimesecond(from.starttimesecond());
  }
  if (from.endtimefirst() != 0) {
    set_endtimefirst(from.endtimefirst());
  }
  if (from.endtimesecond() != 0) {
    set_endtimesecond(from.endtimesecond());
  }
  if (from.returnnode() != 0) {
    set_returnnode(from.returnnode());
  }
}

void NetflowEdgeRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sam.NetflowEdgeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetflowEdgeRequest::CopyFrom(const NetflowEdgeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sam.NetflowEdgeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetflowEdgeRequest::IsInitialized() const {
  return true;
}

void NetflowEdgeRequest::Swap(NetflowEdgeRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NetflowEdgeRequest::InternalSwap(NetflowEdgeRequest* other) {
  using std::swap;
  sourceip_.Swap(&other->sourceip_);
  destip_.Swap(&other->destip_);
  swap(starttimefirst_, other->starttimefirst_);
  swap(starttimesecond_, other->starttimesecond_);
  swap(endtimefirst_, other->endtimefirst_);
  swap(endtimesecond_, other->endtimesecond_);
  swap(returnnode_, other->returnnode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NetflowEdgeRequest::GetMetadata() const {
  protobuf_NetflowEdgeRequest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_NetflowEdgeRequest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sam

// @@protoc_insertion_point(global_scope)
